name: quoridor
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
      - backend

networks:
  network: